name: couclient
description: 'Children of Ur :: Webclient'
dependencies:
  browser: any
  dnd: any
  firebase: '>=0.5.0 <0.6.0'
  gorgon: any
  intl: any
  libld:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/libld.git
  paper_elements: ">=0.7.0 <0.8.0"
  polymer: '>=0.16.1+4 < 0.17.0'
  pump:
    git:
      ref: master
      url: git://github.com/ppvk/pump.git
  redstone_mapper: '0.2.0-beta.1'
  scproxy:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/scproxy.git
  slack:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/dart-slack.git
  cou_auction_house:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/auction_house.git
  cou_toolkit:
      git:
        ref: master
        url: git://github.com/ChildrenOfUr/cou_toolkit.git
  cou_login:
      git:
        ref: dev
        url: https://github.com/ChildrenOfUr/cou_login.git

transformers:
- redstone_mapper
- polymer:
    entry_points:
    - web/index.html