name: couclient
description: 'Children of Ur :: Webclient'
dependencies:
  browser: any
  dnd: any
  firebase: '>=0.5.0 <0.6.0'
  gorgon: any
  intl: any
  libld:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/libld.git
  paper_elements: '>=0.6.2+3 <0.7.0'
  polymer: '>=0.16.0+7 < 0.17.0'
  pump:
    git:
      ref: master
      url: git://github.com/ppvk/pump.git
  redstone_mapper: '>=0.1.13 <0.2.0'
  scproxy:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/scproxy.git
  slack:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/dart-slack.git
transformers:
- redstone_mapper
- polymer:
    entry_points:
    - web/index.html
    - web/demo/toolkit.html
