name: couclient
description: 'Children of Ur :: Webclient'
dependencies:
  async_await:
    git: https://github.com/dart-lang/async_await.git
  browser: any
  dnd: any
  gorgon: any
  intl: any
  libld:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/libld.git
  persona:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/dart-persona.git
  polymer: any
  pump:
    git:
      ref: master
      url: git://github.com/ppvk/pump.git
  redstone_mapper: any
  scproxy:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/scproxy.git
  slack:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/dart-slack.git
transformers:
- redstone_mapper
- async_await
- polymer:
    entry_points:
    - web/index.html
