name: coUclient
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur client
homepage: ChildrenOfUr.github.io
dependencies:
  box2d: any
  browser: any
  game_loop: any
  glitchTime:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/glitch-time.dart.git
  intl: any
  loadie:
    path: ../loadie
  scproxy:
    git:
      ref: master
      url: https://github.com/darkkiero/scproxy.git
