name: coUclient
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur client
homepage: ChildrenOfUr.github.io
dependencies:
  asset_pack: any
  box2d: any
  browser: any
  coUlib:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/coUlib.git
  dartemis: any
  game_loop: any
