name: couclient
description: 'Children of Ur :: Webclient'
dependencies:
  async_await:
    git: https://github.com/dart-lang/async_await.git
  browser: any
  dnd: any
  gorgon: any
  intl: any
  libld:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/libld.git
  polymer: ">=0.12.0 <0.16.0"
  firebase: ">=0.5.0 <0.6.0"
  pump:
    git:
      ref: master
      url: git://github.com/ppvk/pump.git
  redstone_mapper: any
  scproxy:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/scproxy.git
  slack:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/dart-slack.git

transformers:
- redstone_mapper
- async_await
- polymer:
    entry_points:
    - web/index.html
    - web/demo/toolkit.html
- couclient/transformers/cache_break_transformer
