name: coUclient
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur client
homepage: ChildrenOfUr.github.io
dependencies:
  dnd: '>=0.1.3 <0.2.0'
  glitch_time: any
  gorgon: '>=0.13.3'
  intl: any
  libld:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/libld
  scproxy:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/scproxy.git