name: coUclient
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur client
homepage: ChildrenOfUr.github.io
dependencies:
  glitch_time: any
  grinder: any
  intl: any
  libld:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/libld
  scproxy:
    git:
      ref: master
      url: https://github.com/darkkiero/scproxy.git
  gorgon: '>=0.13.3'