name: couclient
description: 'Children of Ur :: Webclient'
dependencies:
  browser: any
  dnd: any
  gorgon: any
  intl: any
  libld:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/libld.git
  persona:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/dart-persona.git
  pump:
    git:
      ref: master
      url: git://github.com/ppvk/pump.git
  scproxy:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/scproxy.git
  slack:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/dart-slack.git
transformers:
- $dart2js:
    minify: true
