name: coUclient
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur client
homepage: ChildrenOfUr.github.io
dependencies:
  bootjack: any
  glitchTime:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/glitch-time.dart.git
  gloss: any
  grinder: any
  intl: any
  loadie:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/loadie.git
  scproxy:
    git:
      ref: master
      url: https://github.com/darkkiero/scproxy.git
